### ISSUE TITLE
Implement Model Runner in the Terminal

### ISSUE THREAD

**Issue by MattCMK** [credmark/credmark-terminal#32]
Implement the **app.credmark.com/models/run** functionality into the Terminal by adding a new category **Model Runner* into the section **Credmark Analytics**

**Comment by MattCMK** [comment]
@v1nvn this is working fine - can you push it to prod standalone?

**Comment by v1nvn** [comment]
@MattCMK standalone? Should I push only this change to app.credmark.com, and not include the FRAX power BI dashboards?

**Comment by MattCMK** [comment]
@v1nvn yes sorry- if it is possible then please push only the model runner to prod - we wait with the FRAX stuff until the new design is ready

**Comment by v1nvn** [comment]
@MattCMK Perfect! I'll deploy it to prod.

There are 2 more small changes in the pipeline:
 - CMK as a default token in sharpe ratio page
 - sub categories in model overview page

Should I push them to prod as well or wait for the new design?

**Comment by MattCMK** [comment]
@v1nvn Yeah push both as well - that is fine -thank you
