### ISSUE TITLE
Re-Design Terminal

### ISSUE THREAD

**Issue by v1nvn** [credmark/credmark-terminal#35]
https://www.figma.com/file/8Bfv8YaIytQwkIih6qeMxn/Design%2FApp?node-id=2314%3A30366

**Comment by MattCMK** [comment]
@v1nvn I added this to the current sprint - Mark has finished the Design. It contains Dark Mode but some layout changes as well. Please make sure to pay attention to the following order of the categories :
1. DEX will move to the top
2. Lenders will be the second category
3. Financial Metrics - this shall include Sharpe Ratio and the FRAX Dashboards, leave out Stablecoin Health and Protocol Analytics for now
4. Credmark Analytics
