### ISSUE TITLE
Terminal cleanup post CMK delisting

### ISSUE THREAD

**Issue by murphy** [credmark/credmark-terminal#52]
* Remove "Stake CMK"
* Remove "Credmark Analytics / Token Analytics"

Is there any reason to keep "Connect Wallet"?

**Comment by v1nvn** [comment]
@murphy "Connect Wallet" is only being used by stake/unstake CMK. It's not being used anywhere else, so there is no reason to keep it.

**Comment by v1nvn** [comment]
@MattCMK This will remove `Token Analytics` from `Credmark Analytics` section of the sidebar. The remaining links in that section will be 
- Model Overview
- Model Runner
- Model Usage

Should we rename `Credmark Analytics` heading to something more apt?

**Comment by MattCMK** [comment]
> 

Hi @v1nvn sure. make sense to rename it to ``Model Analytics``

**Comment by v1nvn** [comment]
fixed in 486323c29a94365fb68370dd098c992fdd511d1e
